# permissions for end users to view operands.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: math-operator
    app.kubernetes.io/managed-by: kustomize
  name: operand-viewer-role
rules:
- apiGroups:
  - batch.math.operator.com
  resources:
  - operands
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.math.operator.com
  resources:
  - operands/status
  verbs:
  - get
