# permissions for end users to view results.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: math-operator
    app.kubernetes.io/managed-by: kustomize
  name: result-viewer-role
rules:
- apiGroups:
  - batch.math.operator.com
  resources:
  - results
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.math.operator.com
  resources:
  - results/status
  verbs:
  - get
